# Generated by Django 4.1.2 on 2022-11-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='cumple',
            new_name='cultimo_log',
        ),
    ]
