# Generated by Django 4.1.2 on 2022-11-04 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0002_rename_cumple_familia_cultimo_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='cultimo_log',
            new_name='ultimo_log',
        ),
    ]
