# Generated by Django 4.1.2 on 2022-11-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0003_rename_cultimo_log_familia_ultimo_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='ultimo_log',
        ),
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
